# Generated by Django 4.2.6 on 2023-10-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('about', models.TextField(blank=True, null=True)),
                ('fb_url', models.CharField(blank=True, max_length=225, null=True)),
                ('insta_url', models.CharField(blank=True, max_length=225, null=True)),
                ('x_url', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
