# Generated by Django 4.2.6 on 2023-10-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
